### ISSUE TITLE
Error Message after I create a new space

### ISSUE THREAD

**Issue by sabdul14** [FordLabs/PeopleMover#224] opened 2020-07-27 21:25 UTC
# Feature Request

## Story
**As a** peoplemover user
**I want** to be able to access the new space I just created without an error message
**So** that I know I am not doing anything wrong

----

## Acceptance Criteria
**Given** I create a new space
**When** I click it
**Then** I don't get a 404 error message

## Notes
Sara & Mike experienced this on Monday 7/27 when they tried creating a new space. They got error messages at first. Sara left the dashboard and clicked back, then it worked. Mike had to log out and then log back in for it to work without getting an error message.

**Comment by alexwojtala** [comment] 2020-07-31 17:48
Could not reproduce in stage

Was able to reproduce this in prod, but could not reproduce this in stage. May have been fixed by implementation of ADFS. I recommend pushing to prod when ADFS is complete and rechecking this bug.

**Closed** 2020-08-11 17:01 UTC
Labels: :stop_sign: !, BUG
